name: boilerplates

networks:
  intranet:
    external: true

services:
  golang:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/Dockerfile.development
    env_file:
      - .env.development
    ports:
      - '3000:8080'
    volumes:
      - ./src:/app
    networks:
      - intranet
    command: sh -c "go run cmd/server/main.go"