swagger: "2.0"
info:
  description: "This is a sample server for a Go API service."
  version: "1.0.0"
  title: "Go API Service"
host: "localhost:8080"
basePath: "/api/v1"
schemes:
- "http"
paths:
  /users:
    get:
      summary: "Get all users"
      description: "Returns a list of users."
      produces:
      - "application/json"
      responses:
        200:
          description: "A list of users."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
definitions:
  User:
    type: "object"
    required:
    - "name"
    - "email"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      email:
        type: "string"